# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PROF_DATA": "01_profiling.ipynb",
         "profile_call": "01_profiling.ipynb",
         "print_prof_data": "01_profiling.ipynb",
         "clear_prof_data": "01_profiling.ipynb",
         "get_prof_data": "01_profiling.ipynb",
         "start_record": "01_profiling.ipynb",
         "end_record": "01_profiling.ipynb",
         "save_prof_data": "01_profiling.ipynb",
         "load_prof_data": "01_profiling.ipynb"}

modules = ["profiling.py"]

doc_url = "https://butchland.github.io/my_timesaver_utils/"

git_url = "https://github.com/butchland/my_timesaver_utils/tree/master/"

def custom_doc_links(name): return None
