# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_enhanced_jmd_imagecleaner.ipynb (unless otherwise specified).

__all__ = ["hello_world"]


# Cell
def hello_world(msg="hello world!"):
    print(msg)
    return msg
